【PR】: 代码化流水线增加冒烟任务
Co-authored-by: liuyi<larry.liuyi@huawei.com>



# message auto-generated for no-merge-commit merge:
!3450 merge ci into ci

【PR】: 代码化流水线增加冒烟任务

Created-by: Larry_liuyi
Commit-by: liuyi
Merged-by: cann-robot
Description: 
# Pull Request

## 描述
代码化流水线增加冒烟任务

## 变更类型
请选择本次引入的变更类型：
<!--  [x] 表示选中 -->
- [ ] 🐛 Bug 修复
- [ ] ✨ 新功能
- [ ] 💄 代码风格更新（格式化，局部变量）
- [ ] ♻️ 重构（既不修复错误也不增加功能的代码变动）
- [ ] 📦 构建过程或辅助工具的变动
- [ ] 📝 文档内容更新

## 关联的Issue
<!-- 如果这个PR是为了解决特定的Issue，请在当前页面的右侧'关联Issue'部分添加相应Issue链接，并勾选'合并后关闭已关联的 Issue'选项。 -->


## 如何测试
描述测试此变更的步骤和前提条件：
1.
2.

## 核对清单
<!--  [x] 表示选中 -->
- [ ] 我的代码遵循了项目的代码风格
- [ ] 我已对代码进行了自测
- [ ] 我已更新了相关的文档
- [ ] 我在标题中使用了合适的类型标签（如：`feat:`, `fix:`）
- [ ] 我已经详细阅读了贡献指南（CONTRIBUTING.md），并遵守了其中的所有规定，包括但不限于commit message的格式、无效commit的合并等

## 其他信息
在此添加任何其他关于本次 PR 的说明。

See merge request: cann/runtime!3450

diff --git a/.gitcode/workflows/runtime_action.yml b/.gitcode/workflows/runtime_action.yml
--- a/.gitcode/workflows/runtime_action.yml
+++ b/.gitcode/workflows/runtime_action.yml
@@ -9,6 +9,11 @@ concurrency:
     events: [mr_id] 
 
 on:
+  workflow_dispatch:
+    inputs:
+      build_id:
+        required: true
+        type: number
   pull_request_comment:
     types: [created]
     branches: [ '*' ]
@@ -21,6 +26,7 @@ env:
   org_name: "cann"
   repo_name: "runtime"
   obs_path: "${{ vars.OBS_PATH}}/${{ env.MERGE_ID }}"
+  obs_smoke_path: "presmoke/runtime/a2/${{ env.MERGE_ID }}"
 
 stages:
   stage1:
@@ -55,7 +61,7 @@ stages:
             identifier: process_checkout
             uses: checkout
             with:
-              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
+              ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
               token: ${{secrets.GIT_TOKEN}}
           -
             name: get_pr
@@ -333,7 +339,7 @@ stages:
             identifier: process_checkout
             uses: checkout
             with:
-              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
+              ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
               token: ${{secrets.GIT_TOKEN}}
           -
             name: download
@@ -383,7 +389,7 @@ stages:
             identifier: process_checkout
             uses: checkout
             with:
-              ref: ${{ atomgit.event.pull_request.merge_commit_sha }}
+              ref: ${{ atomgit.event.pull_request.merge_commit_sha || atomgit.sha }}
               token: ${{secrets.GIT_TOKEN}}
           -
             name: download
@@ -423,6 +429,107 @@ stages:
         runs-on: [dedicate-hosted, x64, large]
         container:
           image: swr.cn-north-4.myhuaweicloud.com/ci_cann/ubuntu24.04_x86:lv6_v1.1073
+    pre:
+    - type: auto
+    fail-fast: true
+  stage5:
+    name: PreSmoke
+    jobs:
+      A2_smoke:
+        name: A2_pre_smoke
+        steps:
+          - 
+            name: Checkout
+            identifier: process_checkout
+            uses: checkout
+            with:
+              path: "./runner"
+          - 
+            name: Checkout gitcode
+            identifier: process_checkout_gitcode
+            uses: checkout
+            with:
+              repository: "https://gitcode.com/cann/.gitcode.git"
+              ref: master
+              path: "./runner/ci"
+          - name: download run file
+            identifier: process_download
+            uses: obs-download
+            with:
+              endpoint: "obs.cn-north-4.myhuaweicloud.com"
+              bucket: "ascend-ci"
+              key: "${{jobs.JOB_arm_compile_ubuntu24.outputs.arm_run_key}}"
+              path: ${{ steps.process_checkout.outputs.path }}
+          -
+            name: tar businesscode
+            run: |
+              cd ${{ steps.process_checkout.outputs.path }}           
+              tar -zcf ../smoke_data.tar.gz .
+              mv ../smoke_data.tar.gz ./
+          - 
+            name: upload
+            identifier: process_upload
+            uses: obs-upload
+            with:
+              endpoint: "https://obs.cn-north-4.myhuaweicloud.com"
+              bucket: "ascend-ci"
+              access-key: ${{secrets.AK}}
+              secret-key: ${{secrets.SK}}
+              artifact-path: |
+                ${{ steps.process_checkout.outputs.path }}/smoke_data.tar.gz
+              object-prefix: ${{ env.obs_smoke_path }}/
+          - 
+            name: smoke executor
+            uses: manifest-management-plugin
+            with:
+              action: DEPLOY
+              repo: ${{ steps.process_checkout.outputs.path }}
+              file_path: ${{ steps.process_checkout.outputs.path }}/ci/smoke-conf/smoke-A2.yaml
+              manifest_image: swr.cn-south-1.myhuaweicloud.com/pre_smoke/${{ jobs.JOB_image.outputs.Smoke_A900_npupool }}
+              custom_shell_script: |-
+                mkdir -p /home/taskspace && cd /home/taskspace
+                echo "start run test case, please wait ..."
+                export ASCEND_GLOBAL_LOG_LEVEL=2
+                export ASCEND_SLOG_PRINT_TO_STDOUT=0
+                source /usr/local/Ascend/cann/set_env.sh
+                echo "1. downaload rttest_data.zip"
+                wget -nv https://opencann-obs.obs.cn-north-4.myhuaweicloud.com/ci/rttest_data.zip && unzip -q rttest_data.zip
+                echo "2. download businesscode"
+                wget -nv ${{ steps.process_upload.outputs.primary-url }}
+                tar -zxf $(basename "${{ steps.process_upload.outputs.primary-url }}")
+                # 安装 runtime 包到 /usr/local/Ascend
+                filename=$(basename "${{ steps.process_download.outputs.download-path }}")
+                yes "y" | bash ${filename} --full --install-path=/usr/local/Ascend --quiet
+                path=$(pwd)
+                source /usr/local/Ascend/cann/set_env.sh
+                bash scripts/pre-smoking.sh ${path}/rtstest_host 2>&1 | tee -a ./run_test.log
+                echo "Run all examples success" >> ./run_test.log
+                # 打包plog
+                mkdir -p /root/ascend
+                slog_name="slog.tar.gz"
+                tar -zcf slog.tar.gz -C /root/ascend log
+                # upload plog
+                if python3 /home/upload.py --bucket-name "ascend-ci" --action upload  --local-file "slog.tar.gz" --obs-object-key "${{env.repo_name}}/package/${{ env.MERGE_ID }}/${slog_name}" --ak "${{secrets.AK}}" --sk "${{secrets.SK}}"; then
+                  echo "::set-output var=plog_url:https://ascend-ci.obs.cn-north-4.myhuaweicloud.com/${{env.repo_name}}/package/${{ env.MERGE_ID }}/slog.tar.gz"
+                fi
+                npu-smi info
+                echo "4. checking test results ..."
+                date_time=`date +%Y%m%d`"."`date +%H%M%S`
+                if grep -w -e "Run all examples success" "./run_test.log"; then
+                  echo "$date_time : run test case success"
+                else
+                  echo "$date_time : run test case failed"
+                  exit 1
+                fi
+          - 
+            name: smoke resource clean
+            uses: manifest-management-plugin
+            with:
+              action: CRUSH
+              repo: ${{ steps.process_checkout.outputs.path }}
+              file_path: ${{ steps.process_checkout.outputs.path }}/ci/smoke-conf/smoke-A2.yaml
+        if: "${{ default() }}"
+        runs-on: ['self-hosted','arch=arm','smoke=204']
     pre:
     - type: auto
     fail-fast: true
